import { DollarSign, Package, ShoppingCart, Star } from "lucide-react";

export const initialMerchantData = {
  name: "Chanel",
  email: "contact@chanel.com",
  phone: "+33 1 44 50 73 00",
  website: "https://chanel.com",
  address: "135 Avenue Charles de Gaulle, 92200 Neuilly-sur-Seine, France",
  description: "Timeless elegance and sophisticated luxury fashion.",
  category: "Fashion",
  commission: 15,
  status: "ACTIVE",
};

export const initialProducts = [
  {
    id: "PRD-001",
    name: "Silk Evening Gown",
    price: "$2,850",
    status: "ACTIVE",
  },
  { id: "PRD-002", name: "Leather Handbag", price: "$4,200", status: "ACTIVE" },
  {
    id: "PRD-003",
    name: "Designer Sunglasses",
    price: "$350",
    status: "PENDING",
  },
];

export const stats = [
  {
    title: "Total Products",
    value: "245",
    change: "+12",
    changeType: "positive" as const,
    icon: Package,
  },
  {
    title: "Total Orders",
    value: "1,247",
    change: "+23%",
    changeType: "positive" as const,
    icon: ShoppingCart,
  },
  {
    title: "Revenue",
    value: "$156,789",
    change: "+18%",
    changeType: "positive" as const,
    icon: DollarSign,
  },
  {
    title: "Store Rating",
    value: "4.9",
    change: "+0.2",
    changeType: "positive" as const,
    icon: Star,
  },
];

export const recentOrders = [
  {
    id: "ORD-001",
    customer: "Sarah Johnson",
    product: "Silk Evening Gown",
    amount: "$2,850",
    status: "COMPLETED",
    date: "2024-01-15",
  },
  {
    id: "ORD-002",
    customer: "Michael Chen",
    product: "Leather Handbag",
    amount: "$4,200",
    status: "SHIPPED",
    date: "2024-01-14",
  },
  {
    id: "ORD-003",
    customer: "Emma Wilson",
    product: "Designer Sunglasses",
    amount: "$350",
    status: "PROCESSING",
    date: "2024-01-13",
  },
];

export const topProducts = [
  {
    id: "PRD-001",
    name: "Silk Evening Gown",
    sales: 45,
    revenue: "$128,250",
    rating: 4.8,
  },
  {
    id: "PRD-002",
    name: "Leather Handbag",
    sales: 32,
    revenue: "$134,400",
    rating: 4.9,
  },
  {
    id: "PRD-003",
    name: "Designer Sunglasses",
    sales: 78,
    revenue: "$27,300",
    rating: 4.5,
  },
];

export const inventoryData = [
  {
    id: "PRD-001",
    name: "Silk Evening Gown",
    sku: "SEG-001",
    category: "Dresses",
    currentStock: 5,
    minStock: 2,
    maxStock: 20,
    price: 2850,
    cost: 1200,
    status: "IN_STOCK",
    lastUpdated: "2024-01-15",
    image:
      "https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&w=300",
    sales30Days: 12,
    revenue30Days: 34200,
    stockValue: 14250,
    reorderPoint: 3,
    supplier: "Luxury Fabrics Inc.",
    location: "Warehouse A-1",
  },
  {
    id: "PRD-002",
    name: "Leather Handbag",
    sku: "LHB-002",
    category: "Bags",
    currentStock: 1,
    minStock: 3,
    maxStock: 15,
    price: 4200,
    cost: 2100,
    status: "LOW_STOCK",
    lastUpdated: "2024-01-14",
    image:
      "https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300",
    sales30Days: 8,
    revenue30Days: 33600,
    stockValue: 4200,
    reorderPoint: 3,
    supplier: "Premium Leather Co.",
    location: "Warehouse B-2",
  },
  {
    id: "PRD-003",
    name: "Designer Sunglasses",
    sku: "DSG-003",
    category: "Accessories",
    currentStock: 0,
    minStock: 5,
    maxStock: 25,
    price: 350,
    cost: 150,
    status: "OUT_OF_STOCK",
    lastUpdated: "2024-01-13",
    image:
      "https://images.pexels.com/photos/1263986/pexels-photo-1263986.jpeg?auto=compress&cs=tinysrgb&w=300",
    sales30Days: 25,
    revenue30Days: 8750,
    stockValue: 0,
    reorderPoint: 5,
    supplier: "Eyewear Distributors",
    location: "Warehouse C-3",
  },
  {
    id: "PRD-004",
    name: "Cashmere Coat",
    sku: "CC-004",
    category: "Outerwear",
    currentStock: 15,
    minStock: 3,
    maxStock: 12,
    price: 1890,
    cost: 950,
    status: "OVER_STOCK",
    lastUpdated: "2024-01-12",
    image:
      "https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=300",
    sales30Days: 3,
    revenue30Days: 5670,
    stockValue: 28350,
    reorderPoint: 3,
    supplier: "Cashmere Mills Ltd.",
    location: "Warehouse A-2",
  },
];

export const orders = [
  {
    id: "ORD-001",
    orderNumber: "#LX-2024-001",
    customer: {
      name: "Sarah Johnson",
      email: "sarah.johnson@email.com",
      phone: "+1 (555) 123-4567",
      address: "123 Fifth Ave, New York, NY 10001",
    },
    products: [
      {
        id: "PRD-001",
        name: "Silk Evening Gown",
        sku: "SEG-001",
        quantity: 1,
        price: 2850,
        size: "M",
        color: "Black",
      },
    ],
    subtotal: 2850,
    shipping: 0,
    tax: 228,
    total: 3078,
    status: "PENDING",
    paymentStatus: "PAID",
    orderDate: "2024-01-15T10:30:00Z",
    estimatedDelivery: "2024-01-20",
    shippingMethod: "Express Delivery",
    trackingNumber: null,
    notes: "Customer requested gift wrapping",
  },
  {
    id: "ORD-002",
    orderNumber: "#LX-2024-002",
    customer: {
      name: "Michael Chen",
      email: "michael.chen@email.com",
      phone: "+1 (555) 987-6543",
      address: "456 Park Ave, Los Angeles, CA 90210",
    },
    products: [
      {
        id: "PRD-002",
        name: "Leather Handbag",
        sku: "LHB-002",
        quantity: 1,
        price: 4200,
        size: "One Size",
        color: "Brown",
      },
    ],
    subtotal: 4200,
    shipping: 25,
    tax: 336,
    total: 4561,
    status: "PROCESSING",
    paymentStatus: "PAID",
    orderDate: "2024-01-14T14:20:00Z",
    estimatedDelivery: "2024-01-19",
    shippingMethod: "Standard Delivery",
    trackingNumber: "TRK123456789",
    notes: null,
  },
  {
    id: "ORD-003",
    orderNumber: "#LX-2024-003",
    customer: {
      name: "Emma Wilson",
      email: "emma.wilson@email.com",
      phone: "+1 (555) 456-7890",
      address: "789 Madison Ave, Chicago, IL 60611",
    },
    products: [
      {
        id: "PRD-003",
        name: "Designer Sunglasses",
        sku: "DSG-003",
        quantity: 2,
        price: 350,
        size: "One Size",
        color: "Black",
      },
    ],
    subtotal: 700,
    shipping: 15,
    tax: 56,
    total: 771,
    status: "SHIPPED",
    paymentStatus: "PAID",
    orderDate: "2024-01-13T09:15:00Z",
    estimatedDelivery: "2024-01-18",
    shippingMethod: "Standard Delivery",
    trackingNumber: "TRK987654321",
    notes: null,
  },
  {
    id: "ORD-004",
    orderNumber: "#LX-2024-004",
    customer: {
      name: "David Brown",
      email: "david.brown@email.com",
      phone: "+1 (555) 321-0987",
      address: "321 Broadway, Miami, FL 33101",
    },
    products: [
      {
        id: "PRD-004",
        name: "Cashmere Coat",
        sku: "CC-004",
        quantity: 1,
        price: 1890,
        size: "L",
        color: "Navy",
      },
    ],
    subtotal: 1890,
    shipping: 0,
    tax: 151,
    total: 2041,
    status: "DELIVERED",
    paymentStatus: "PAID",
    orderDate: "2024-01-10T16:45:00Z",
    estimatedDelivery: "2024-01-15",
    shippingMethod: "Express Delivery",
    trackingNumber: "TRK456789123",
    notes: null,
  },
];
