export const orders = [
  {
    id: "ORD-001",
    customer: {
      name: "Sarah Johnson",
      email: "sarah.johnson@email.com",
    },
    merchant: "Versace",
    products: [{ name: "Silk Evening Gown", quantity: 1, price: 2850 }],
    total: 2850,
    status: "COMPLETED",
    paymentStatus: "PAID",
    shippingAddress: "123 Fifth Ave, New York, NY 10001",
    orderDate: "2024-01-15",
    deliveryDate: "2024-01-18",
  },
  {
    id: "ORD-002",
    customer: {
      name: "Michael Chen",
      email: "michael.chen@email.com",
    },
    merchant: "Gucci",
    products: [
      { name: "Leather Wallet", quantity: 1, price: 450 },
      { name: "Designer Belt", quantity: 1, price: 750 },
    ],
    total: 1200,
    status: "PROCESSING",
    paymentStatus: "PAID",
    shippingAddress: "456 Park Ave, Los Angeles, CA 90210",
    orderDate: "2024-01-15",
    deliveryDate: null,
  },
  {
    id: "ORD-003",
    customer: {
      name: "Emma Wilson",
      email: "emma.wilson@email.com",
    },
    merchant: "Hermès",
    products: [{ name: "Leather Handbag", quantity: 1, price: 4500 }],
    total: 4500,
    status: "SHIPPED",
    paymentStatus: "PAID",
    shippingAddress: "789 Madison Ave, Chicago, IL 60611",
    orderDate: "2024-01-14",
    deliveryDate: "2024-01-17",
  },
  {
    id: "ORD-004",
    customer: {
      name: "David Brown",
      email: "david.brown@email.com",
    },
    merchant: "Prada",
    products: [{ name: "Designer Shoes", quantity: 1, price: 890 }],
    total: 890,
    status: "PENDING",
    paymentStatus: "PENDING",
    shippingAddress: "321 Broadway, Miami, FL 33101",
    orderDate: "2024-01-14",
    deliveryDate: null,
  },
  {
    id: "ORD-005",
    customer: {
      name: "Lisa Anderson",
      email: "lisa.anderson@email.com",
    },
    merchant: "Tiffany & Co.",
    products: [{ name: "Diamond Necklace", quantity: 1, price: 8500 }],
    total: 8500,
    status: "CANCELLED",
    paymentStatus: "REFUNDED",
    shippingAddress: "654 Ocean Drive, San Francisco, CA 94102",
    orderDate: "2024-01-13",
    deliveryDate: null,
  },
];
